; #FUNCTION# ====================================================================================================================
; Name ..........: MBR GUI Design
; Description ...: This file Includes GUI Design
; Syntax ........:
; Parameters ....: None
; Return values .: None
; Author ........: GKevinOD (2014)
; Modified ......: DkEd, Hervidero (2015)
; Remarks .......: This file is part of MyBot, previously known as ClashGameBot. Copyright 2015-2016
;                  MyBot is distributed under the terms of the GNU GPL
; Related .......:
; Link ..........: https://github.com/MyBotRun/MyBot/wiki
; Example .......: No
; ===============================================================================================================================

;~ -------------------------------------------------------------
;~ Notify Tab
;~ -------------------------------------------------------------
$tabNotify = GUICtrlCreateTabItem(GetTranslated(9,1, "Notify"))
	Local $x = 30, $y = 150
	$grpPushBullet = GUICtrlCreateGroup(GetTranslated(9,2, "PushBullet And Telegram Alert"), $x - 20, $y - 23, 450, 375)
;	$picPushBullet = GUICtrlCreateIcon ($pIconLib, $eIcnPushBullet, $x, $y, 32, 32)
	$picPushBullet = GUICtrlCreatePic(@ScriptDir & "\Images\PTNIcon75.jpg", $x - 14, $y, 47, 23)
	$chkPBenabled = GUICtrlCreateCheckbox(GetTranslated(9,3, "Enable Pushbullet"), $x + 40, $y - 10)
		GUICtrlSetOnEvent(-1, "chkPBenabled")
		GUICtrlSetTip(-1, GetTranslated(9,4, "Enable PushBullet notifications"))
	$chkPBenabled2 = GUICtrlCreateCheckbox("Enable Telegram", $x + 40, $y +10 )
	    GUICtrlSetOnEvent(-1, "chkPBenabled2")
	    GUICtrlSetTip(-1, "Enable Telegram notifications")
	$y += 32
	$chkPBRemote = GUICtrlCreateCheckbox(GetTranslated(9,5, "Remote Control"), $x + 40, $y)
		GUICtrlSetTip(-1, GetTranslated(9,6, "Enables PushBullet Remote function"))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y = 150
	$chkDeleteAllPushes = GUICtrlCreateCheckbox(GetTranslated(9,7, "Delete Msg on Start"), $x + 160, $y)
		GUICtrlSetTip(-1, GetTranslated(9,8, "It will delete all previous push notification when you start bot"))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$btnDeletePBmessages = GUICtrlCreateButton(GetTranslated(9,9, "Delete all Msg now"), $x + 300, $y, 100, 20)
		GUICtrlSetTip(-1, GetTranslated(9,10, "Click here to delete all Pushbullet messages."))
		GUICtrlSetOnEvent(-1, "btnDeletePBMessages")
		IF $btnColor then GUICtrlSetBkColor(-1, 0x5CAD85)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 22
	$chkDeleteOldPushes = GUICtrlCreateCheckbox(GetTranslated(9,11, "Delete Msg older than"), $x + 160, $y)
		GUICtrlSetTip(-1, GetTranslated(9,12, "Delete all previous push notification older than specified hour"))
		GUICtrlSetState(-1, $GUI_DISABLE)
		GUICtrlSetOnEvent(-1, "chkDeleteOldPushes")
	$cmbHoursPushBullet = GUICtrlCreateCombo("", $x + 300, $y, 100, 35, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
		GUICtrlSetTip(-1, GetTranslated(9,13, "Set the interval for messages to be deleted."))
		$sTxtHours = GetTranslated(9,15, "Hours")
		GUICtrlSetData(-1, "1 " & GetTranslated(9,14, "Hour") &"|2 " & $sTxtHours & "|3 " & $sTxtHours & "|4 " & $sTxtHours & "|5 " & $sTxtHours & "|6 " & $sTxtHours & "|7 " & $sTxtHours & "|8 " &$sTxtHours & "|9 " & $sTxtHours & "|10 " & $sTxtHours & "|11 " & $sTxtHours & "|12 " & $sTxtHours & "|13 " & $sTxtHours & "|14 " & $sTxtHours & "|15 " & $sTxtHours & "|16 " & $sTxtHours & "|17 " & $sTxtHours & "|18 " & $sTxtHours & "|19 " & $sTxtHours & "|20 " & $sTxtHours & "|21 " & $sTxtHours & "|22 " & $sTxtHours & "|23 " & $sTxtHours & "|24 " & $sTxtHours, "-")
		GUICtrlSetState (-1, $GUI_DISABLE)
	$y += 30
	$lblPushBTokenValue = GUICtrlCreateLabel(GetTranslated(9,16, "Pushbullet Access Token") & ":", $x, $y, -1, -1, $SS_RIGHT)
	$PushBTokenValue = GUICtrlCreateInput("", $x + 140, $y - 3, 280, 19)
		GUICtrlSetTip(-1, GetTranslated(9,17, "You need a Token to use PushBullet notifications. Get a token from PushBullet.com"))
		GUICtrlSetState(-1, $GUI_DISABLE)
    $lblPushBTokenValue2 = GUICtrlCreateLabel("Telegram Access Token:", $x+5, $y+23, -1, -1, $SS_RIGHT)
	$PushBTokenValue2 = GUICtrlCreateInput("", $x + 140, $y +21, 280, 19)
		GUICtrlSetTip(-1, "You need a Token to use Telegram notifications. Get a token from @BotFather")
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 25
	$lblOrigPush = GUICtrlCreateLabel(GetTranslated(9,18, "Profile/Village Name") & ":", $x + 220 , $y + 25, -1, -1, $SS_RIGHT)
		$txtTip = GetTranslated(9,19, "Your Profile/Village name - Set this on the Misc Tab under Profiles.")
		GUICtrlSetTip(-1, $txtTip)
	$OrigPushB = GUICtrlCreateLabel("", $x + 330, $y +20, 80, 22, $SS_SUNKEN)
		GUICtrlSetBkColor(-1, 0xF0F0F0)
		GUICtrlSetTip(-1, $txtTip)
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 25
	$lblNotifyWhen = GUICtrlCreateLabel(GetTranslated(9,20, "Send a PushBullet message for these options") & ":", $x, $y, -1, -1, $SS_RIGHT)
	$y += 20
	$chkAlertPBVMFound = GUICtrlCreateCheckbox(GetTranslated(9,21, "Match Found"), $x + 10, $y)
		GUICtrlSetTip(-1, GetTranslated(9,22, "Send the amount of available loot when bot finds a village to Notify."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertPBLastRaid = GUICtrlCreateCheckbox(GetTranslated(9,23, "Last raid as image"), $x + 100, $y)
		GUICtrlSetTip(-1, GetTranslated(9,24, "Send the last raid screenshot."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertPBLastRaidTxt = GUICtrlCreateCheckbox(GetTranslated(9,25, "Last raid as Text"), $x + 210, $y, -1, -1)
		GUICtrlSetState(-1, $GUI_DISABLE)
		GUICtrlSetTip(-1, GetTranslated(9,26, "Send the last raid results as text."))
	$chkAlertPBCampFull = GUICtrlCreateCheckbox(GetTranslated(9,27, "Army Camp Full"), $x + 315, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,28, "Sent an Alert when your Army Camp is full."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 20
	$chkAlertPBWallUpgrade = GUICtrlCreateCheckbox(GetTranslated(9,29, "Wall upgrade"), $x + 10, $y, -1, -1)
		 GUICtrlSetTip(-1, GetTranslated(9,30, "Send info about wall upgrades."))
		 GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertPBOOS = GUICtrlCreateCheckbox(GetTranslated(9,31, "Error: Out Of Sync"), $x + 100, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,32, "Send an Alert when you get the Error: Client and Server out of sync"))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertPBVBreak = GUICtrlCreateCheckbox(GetTranslated(9,33, "Take a break"), $x + 210, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,34, "Send an Alert when you have been playing for too long and your villagers need to rest."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertBuilderIdle = GUICtrlCreateCheckbox(GetTranslated(9,53, "Builder Idle"), $x + 315, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,54, "Send an Alert when at least one builder is idle."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 20
	$chkAlertPBVillage = GUICtrlCreateCheckbox(GetTranslated(9,35, "Village Report"), $x + 10, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,36, "Send a Village Report."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertPBLastAttack = GUICtrlCreateCheckbox(GetTranslated(9,37, "Alert Last Notify"), $x + 100, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,38, "Send info about the Last Notify."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	; IceCube (PushBullet Revamp v1.1)	
	$chkAlertPBOtherDevice = GUICtrlCreateCheckbox(GetTranslated(9,39, "Another device"), $x + 210, $y, -1, -1)
		GUICtrlSetTip(-1, GetTranslated(9,40, "Sent an Alert when your village is connected to from another device."))
		GUICtrlSetState(-1, $GUI_DISABLE)
	$chkAlertTopGain = GUICtrlCreateCheckbox("Top Gain && Zap", $x + 315, $y, -1, -1)
		GUICtrlSetTip(-1, "Send an Alert when a Top Gain & Zap is achived.") 
		GUICtrlSetState(-1, $GUI_DISABLE)	
	$y += 20
	$chkAlertMFSwitch = GUICtrlCreateCheckbox("MF: Switch", $x + 10, $y, -1, -1)
		GUICtrlSetTip(-1, "Send an Alert when Multy-Farming switch account")
		GUICtrlSetState(-1, $GUI_DISABLE)		
	$y = 380
	$btnHelpPushBullet = GUICtrlCreateButton("PushBullet HELP", $x + 205, $y + 90, 100, 20)
	GUICtrlSetTip(-1, "PushBullet HELP - All commands")
	GUICtrlSetOnEvent(-1, "btnHelpPushBullet")
	$btnHelpTelegram = GUICtrlCreateButton("Telegram HELP", $x + 320, $y + 90, 100, 20)
	GUICtrlSetTip(-1, "Telegram HELP - All commands")
	GUICtrlSetOnEvent(-1, "btnHelpTelegram")
	;$lblgrppushbullet = GUICtrlCreateGroup(GetTranslated(9,41, "Remote Control Functions"), $x - 10, $y - 20, 430, 165)
	;	$lblPBdesc = GUICtrlCreateLabel(GetTranslated(9,42, "BOT HELP - send this help message") & @CRLF & GetTranslated(9,43, "BOT DELETE  - delete all your previous PushBullet messages") & @CRLF & _
	;		GetTranslated(9,44, "BOT <Village Name> RESTART - restart the bot named <Village Name> and BlueStacks") & @CRLF & GetTranslated(9,45, "BOT <Village Name> STOP - stop the bot named <Village Name>") & @CRLF & _
	;		GetTranslated(9,46, "BOT <Village Name> PAUSE - pause the bot named <Village Name>") & @CRLF & GetTranslated(9,47, "BOT <Village Name> RESUME   - resume the bot named <Village Name>") & @CRLF & _
	;		GetTranslated(9,48, "BOT <Village Name> STATS - send Village Statistics of <Village Name>") & @CRLF & GetTranslated(9,49, "BOT <Village Name> LOG - send the current log file of <Village Name>") & @CRLF & _
	;		GetTranslated(9,50, "BOT <Village Name> LASTRAID -  send the last raid loot screenshot of <Village Name>") & @CRLF & GetTranslated(9,51, "BOT <Village Name> LASTRAIDTXT - send the last raid loot values of <Village Name>") & @CRLF & _
	;		GetTranslated(9,52, "BOT <Village Name> SCREENSHOT - send a screenshot of <Village Name>" & @CRLF & _
	;		"BOT <Village Name> SCREENSHOTHD - send a screenshot in high resolution of <Village Name>" & @CRLF & _
	;		"BOT <Village Name> BUILDER - send builder information of <Village Name>" & @CRLF & _
	;		"BOT <Village Name> SHIELD - send shield information of <Village Name>" & @CRLF & _
	;		"BOT <Village Name> GAIN - send top gain && zap information of <Village Name>", $x, $y - 5, -1, -1, $SS_LEFT)
	;		$lblPBdesc = GUICtrlCreateLabel(GetTranslated(9,42, "BOT HELP - send this help message"), $x, $y - 5, -1, -1, $SS_LEFT)

	$x = 30
	$grpSchedulerNotify = GUICtrlCreateGroup(GetTranslated(26,24, "Notify Scheduler"), $x - 10, $y - 20, 430, 100)
	$x += 15
	$y += 13
	$chkNotifyHours = GUICtrlCreateCheckbox(GetTranslated(26,25, "Only during these hours of day"), $x-15, $y-7)
	$x -= 20
	$y += 13
	GUICtrlSetOnEvent(-1, "chkNotifyHours")
	$lbNotifyhours1 = GUICtrlCreateLabel(" 0", $x + 30, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours2 = GUICtrlCreateLabel(" 1", $x + 45, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours3 = GUICtrlCreateLabel(" 2", $x + 60, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours4 = GUICtrlCreateLabel(" 3", $x + 75, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours5 = GUICtrlCreateLabel(" 4", $x + 90, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours6 = GUICtrlCreateLabel(" 5", $x + 105, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours7 = GUICtrlCreateLabel(" 6", $x + 120, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours8 = GUICtrlCreateLabel(" 7", $x + 135, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours9 = GUICtrlCreateLabel(" 8", $x + 150, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours10 = GUICtrlCreateLabel(" 9", $x + 165, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours11 = GUICtrlCreateLabel("10", $x + 180, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyhours12 = GUICtrlCreateLabel("11", $x + 195, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 15
	$chkNotifyhours0 = GUICtrlCreateCheckbox("", $x + 30, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours1 = GUICtrlCreateCheckbox("", $x + 45, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours2 = GUICtrlCreateCheckbox("", $x + 60, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours3 = GUICtrlCreateCheckbox("", $x + 75, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours4 = GUICtrlCreateCheckbox("", $x + 90, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours5 = GUICtrlCreateCheckbox("", $x + 105, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours6 = GUICtrlCreateCheckbox("", $x + 120, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours7 = GUICtrlCreateCheckbox("", $x + 135, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours8 = GUICtrlCreateCheckbox("", $x + 150, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours9 = GUICtrlCreateCheckbox("", $x + 165, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours10 = GUICtrlCreateCheckbox("", $x + 180, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours11 = GUICtrlCreateCheckbox("", $x + 195, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhoursE1 = GUICtrlCreateCheckbox("", $x + 211, $y+1, 13, 13, BitOR($BS_PUSHLIKE, $BS_ICON))
	GUICtrlSetImage(-1, $pIconLib, $eIcnGoldStar, 0)
	GUICtrlSetState(-1, $GUI_UNCHECKED + $GUI_DISABLE)
	$txtTip = GetTranslated(26,26, "This button will clear or set the entire row of boxes")
	GUICtrlSetTip(-1, $txtTip)
	GUICtrlSetOnEvent(-1, "chkNotifyhoursE1")
	$lbNotifyhoursAM = GUICtrlCreateLabel("AM", $x + 10, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 15
	$chkNotifyhours12 = GUICtrlCreateCheckbox("", $x + 30, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours13 = GUICtrlCreateCheckbox("", $x + 45, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours14 = GUICtrlCreateCheckbox("", $x + 60, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours15 = GUICtrlCreateCheckbox("", $x + 75, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours16 = GUICtrlCreateCheckbox("", $x + 90, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours17 = GUICtrlCreateCheckbox("", $x + 105, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours18 = GUICtrlCreateCheckbox("", $x + 120, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours19 = GUICtrlCreateCheckbox("", $x + 135, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours20 = GUICtrlCreateCheckbox("", $x + 150, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours21 = GUICtrlCreateCheckbox("", $x + 165, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours22 = GUICtrlCreateCheckbox("", $x + 180, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhours23 = GUICtrlCreateCheckbox("", $x + 195, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyhoursE2 = GUICtrlCreateCheckbox("", $x + 211, $y+1, 13, 13, BitOR($BS_PUSHLIKE, $BS_ICON))
	GUICtrlSetImage(-1, $pIconLib, $eIcnGoldStar, 0)
	GUICtrlSetState(-1, $GUI_UNCHECKED + $GUI_DISABLE)
	$txtTip = GetTranslated(26,27, "This button will clear or set the entire row of boxes")
	GUICtrlSetTip(-1, $txtTip)
	GUICtrlSetOnEvent(-1, "chkNotifyhoursE2")
	$lbNotifyhoursPM = GUICtrlCreateLabel("PM", $x + 10, $y)
	GUICtrlSetState(-1, $GUI_DISABLE)

	Local $x = 270 , $y = 383
	$chkNotifyWeekDays = GUICtrlCreateCheckbox(GetTranslated(26,46, "Notify only in this day of the week"), $x - 10, $y)
	GUICtrlSetOnEvent(-1, "chkNotifyWeekDays")
	$y += 19
	$lbNotifyWeekdays1 = GUICtrlCreateLabel(GetTranslated(26,37, " S"), $x + 30, $y)
	GUICtrlSetTip(-1, GetTranslated(26,29, "Sunday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays2 = GUICtrlCreateLabel(GetTranslated(26,38, " M"), $x + 45, $y)
	GUICtrlSetTip(-1, GetTranslated(26,30, "Monday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays3 = GUICtrlCreateLabel(GetTranslated(26,39, " T"), $x + 60, $y)
	GUICtrlSetTip(-1, GetTranslated(26,31, "Tuesday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays4 = GUICtrlCreateLabel(GetTranslated(26,40, " W"), $x + 75, $y)
	GUICtrlSetTip(-1, GetTranslated(26,32, "Wednesday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays5 = GUICtrlCreateLabel(GetTranslated(26,41, " T"), $x + 90, $y)
	GUICtrlSetTip(-1, GetTranslated(26,33, "Thursday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays6 = GUICtrlCreateLabel(GetTranslated(26,42, " F"), $x + 105, $y)
	GUICtrlSetTip(-1, GetTranslated(26,34, "Friday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$lbNotifyWeekdays7 = GUICtrlCreateLabel(GetTranslated(26,43, " S"), $x + 120, $y)
	GUICtrlSetTip(-1, GetTranslated(26,35, "Saturday"))
	GUICtrlSetState(-1, $GUI_DISABLE)
	$y += 13
	$chkNotifyWeekdays0 = GUICtrlCreateCheckbox("", $x + 30, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays1 = GUICtrlCreateCheckbox("", $x + 45, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays2 = GUICtrlCreateCheckbox("", $x + 60, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays3 = GUICtrlCreateCheckbox("", $x + 75, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays4 = GUICtrlCreateCheckbox("", $x + 90, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays5 = GUICtrlCreateCheckbox("", $x + 105, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)
	$chkNotifyWeekdays6 = GUICtrlCreateCheckbox("", $x + 120, $y, 15, 15)
	GUICtrlSetState(-1, $GUI_CHECKED + $GUI_DISABLE)


	; IceCube (PushBullet Revamp v1.1)	
	GUICtrlCreateGroup("", -99, -99, 1, 1)


	GUICtrlCreateGroup("", -99, -99, 1, 1)
GUICtrlCreateTabItem("")
